module.exports = {

  SELECT_MUNICIPI: 'SELECT_MUNICIPI',
  RECEIVE_MUNICIPIS: 'RECEIVE_MUNICIPIS',
  RECEIVE_PREDICCIO_MUNICIPI: 'RECEIVE_PREDICCIO_MUNICIPI',
  CHANGE_ACTIVE_DAY: 'CHANGE_ACTIVE_DAY'
}